# https://www.openfang.sh/docs/configuration
api_listen = "0.0.0.0:4200"
network_enabled = true

[default_model]
api_key_env = ""
model = "panther-minor"
provider = "panther-minor"

[memory]
decay_rate = 0.05

[provider_urls]
panther-minor = "http://llama-cpp:8000/v1"
