# https://www.openfang.sh/docs/configuration
api_listen = "0.0.0.0:4200"

[default_model]
api_key_env = ""
model = "qwen35-35b-a3b-q8_0"
provider = "panther-minor"

[memory]
decay_rate = 0.05
embedding_provider = "panther-minor"
embedding_model = "qwen3-embedding-0-6b-q8_0"

[provider_urls]
panther-minor = "http://llama-manager:8000/v1"
