name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v5

      - name: Setup node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version-file: package.json

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

  qa:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Quality Assurance
        run: pnpm exec biome ci .

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run tests
        run: pnpm run test

